pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'com.android.application' version '9.2.1' apply false
    id 'io.gitlab.arturbosch.detekt' version '1.23.8' apply false
    id 'com.github.spotbugs' version '6.5.11' apply false
    id 'com.diffplug.spotless' version '8.10.0' apply false
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'trik-gamepad'
include ':app'
