// GENERATED data table: every numeric literal is a measured font metric, not a magic
// number a reader would name - suppress detekt's MagicNumber for the whole file.
@file:Suppress("MagicNumber")

package com.trikset.gamepad2.glyphs

/**
 * GENERATED by scripts/glyph_metrics.py (via build_symbol_font.py) - do not edit.
 *
 * Per-glyph 'render in a row' metrics for the bundled res/font/symbols_mono.ttf. Each metric is a
 * fraction of the font's em (size/density/font-scale invariant):
 *
 * visualHeightEm - central 90%-mass band of the glyph's ink / em. A glyph's VISUAL height at
 * textSize T is T * visualHeightEm, so a row equalizes glyphs by setting textSize =
 * targetVisualHeight / visualHeightEm. medianBiasEm - signed offset of the weighted-ink median from
 * the line-box center (positive = median above center), / em. inkBoxEm - full ink-box height (thin
 * tails included) / em; larger than visualHeightEm for glyphs with thin tails (a triangle's point
 * carries little mass, so the band under-reports its true box). medianBiasEm/inkBoxEm are currently
 * NOT consumed by GlyphRendering (the OFF baseline mode no longer aims at the weighted median) —
 * retained by the generator for optical/regression comparison.
 *
 * LINE_BOX_EM caps the renderer's textSize: Android lays out the glyph's line box (ascent +
 * descent), so textSize * (LINE_BOX_EM + 2*|reserve|) must fit the fixed view or the glyph clips
 * even when its ink box alone would fit, where reserve is the centering offset the smart mode
 * actually pads (0 in the plain OFF mode).
 */
object GlyphMetrics {
  const val LINE_BOX_EM = 1.1650f

  data class GlyphMetric(val visualHeightEm: Float, val medianBiasEm: Float, val inkBoxEm: Float)

  const val REFERENCE = "1"
  const val REFERENCE_CODEPOINT = 0x31
  val REFERENCE_METRIC = GlyphMetric(0.683594f, -0.034668f, 0.729492f)

  private val TABLE: Map<Int, GlyphMetric> =
      mapOf(
          0x2B to GlyphMetric(0.422852f, -0.031738f, 0.516602f), // +
          0x2D to GlyphMetric(0.072266f, -0.070801f, 0.080078f), // -
          0x30 to GlyphMetric(0.665039f, 0.019043f, 0.756836f), // 0
          0x31 to GlyphMetric(0.683594f, -0.034668f, 0.729492f), // 1
          0x32 to GlyphMetric(0.697266f, -0.010254f, 0.742188f), // 2
          0x33 to GlyphMetric(0.696289f, 0.022949f, 0.756836f), // 3
          0x34 to GlyphMetric(0.606445f, -0.025879f, 0.729492f), // 4
          0x35 to GlyphMetric(0.695312f, 0.056152f, 0.744141f), // 5
          0x36 to GlyphMetric(0.677734f, 0.009277f, 0.756836f), // 6
          0x37 to GlyphMetric(0.669922f, 0.164551f, 0.729492f), // 7
          0x38 to GlyphMetric(0.675781f, 0.014160f, 0.756836f), // 8
          0x39 to GlyphMetric(0.676758f, 0.026855f, 0.756836f), // 9
          0x3D to GlyphMetric(0.266602f, -0.090332f, 0.282227f), // =
          0x41 to GlyphMetric(0.636719f, -0.052246f, 0.729492f), // A
          0x42 to GlyphMetric(0.669922f, 0.026855f, 0.729492f), // B
          0x43 to GlyphMetric(0.696289f, 0.017090f, 0.756836f), // C
          0x4C to GlyphMetric(0.667969f, -0.128418f, 0.729492f), // L
          0x4D to GlyphMetric(0.642578f, 0.076660f, 0.729492f), // M
          0x4F to GlyphMetric(0.672852f, 0.018066f, 0.756836f), // O
          0x52 to GlyphMetric(0.658203f, 0.034668f, 0.729492f), // R
          0x55 to GlyphMetric(0.666992f, -0.007324f, 0.744141f), // U
          0x57 to GlyphMetric(0.634766f, -0.002441f, 0.729492f), // W
          0x58 to GlyphMetric(0.664062f, 0.004395f, 0.729492f), // X
          0x59 to GlyphMetric(0.649414f, 0.115723f, 0.729492f), // Y
          0x7C to GlyphMetric(0.897461f, -0.084473f, 0.997070f), // |
          0x21BA to GlyphMetric(0.441406f, -0.094238f, 0.497070f), // ↺
          0x23FB to GlyphMetric(0.556641f, -0.043457f, 0.690430f), // ⏻
          0x23FC to GlyphMetric(0.514648f, 0.000488f, 0.602539f), // ⏼
          0x23FD to GlyphMetric(0.758789f, 0.000488f, 0.874023f), // ⏽
          0x23FE to GlyphMetric(0.668945f, -0.109863f, 0.826172f), // ⏾
          0x25A0 to GlyphMetric(0.537109f, -0.085449f, 0.595703f), // ■
          0x25B2 to GlyphMetric(0.448242f, -0.209473f, 0.595703f), // ▲
          0x25C6 to GlyphMetric(0.408203f, -0.086426f, 0.595703f), // ◆
          0x25CF to GlyphMetric(0.482422f, -0.086426f, 0.601562f), // ●
          0x2699 to GlyphMetric(0.468750f, -0.044434f, 0.603516f), // ⚙
          0x2715 to GlyphMetric(0.382812f, -0.052246f, 0.474609f), // ✕
          0x2B58 to GlyphMetric(0.523438f, 0.000488f, 0.602539f), // ⭘
          0xF0208 to GlyphMetric(0.338867f, 0.000488f, 0.409180f), // md-eye
          0xF0209 to GlyphMetric(0.371094f, 0.011230f, 0.518555f), // md-eye_off
          0xF0553 to GlyphMetric(0.692383f, 0.023926f, 0.874023f), // md-usb
      )

  fun metricFor(glyph: String): GlyphMetric? =
      if (glyph.isEmpty()) null else TABLE[glyph.codePointAt(0)]
}
